

# state_0: [0.0, 0.0, 0.0,     0.707,0.0,0.707,0.0,     0.0,0.0,0.0]
# state_0: [0.3, 0.7, 1.0,     0.707,0.0,0.707,0.0,     0.0,0.0,0.0]
state_0: [4.0, 4.0, 1.0,     1.0,0.0,0.0,0.0,     0.0,0.0,0.0]
robot_arm_len: 0.2
robot_m: 1.0
# robot_width: 0.25
# robot_height: 0.10
# robot_a: 0.18
# robot_b: 0.11
# robot_r: 0.075

#obtscles_pos: [[-1.5,-0.9,0.2],[2,3.2,0.5],[1.0,1.7,0.2]]
#obtscles_r: [0.2, 0.2, 0.2]
obtscles_pos: [[20,20,20]]
obtscles_r: [1]

# obtscles_pos: [[0,0,0]]
# obtscles_r: [2.2]
















